### ISSUE TITLE
Property mutation on Query does not exist

### ISSUE THREAD

**Issue by MattLangsenkamp** [aPureBase/KGraphQL#101]
the source code can be found here: https://github.com/MattLangsenkamp/graphql-no-server

I am trying to build a graphql server to fetch and add location data. I will eventually be using the ktor integration within the kotless project, but I made this repo to iron out the interactions with aws dynamo first.
when I make queries to fetch data all works as i intended. example below. 
`schema.executeBlocking("""
        {
            getAllLocations {
                id
            }
        }
    """.trimIndent()).let(::println)`

however when I add a mutation  as such:
`  mutation {
                deleteLocation(id: "ffffff") 
            }`
to add to the database I get the following error
`Exception in thread "main" com.apurebase.kgraphql.GraphQLError: Property mutation on Query does not exist
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelection(RequestInterpreter.kt:147)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.createExecutionPlan(RequestInterpreter.kt:91)
	at com.apurebase.kgraphql.schema.DefaultSchema$execute$2.invokeSuspend(DefaultSchema.kt:47)
	at com.apurebase.kgraphql.schema.DefaultSchema$execute$2.invoke(DefaultSchema.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:177)
	at com.apurebase.kgraphql.schema.DefaultSchema.execute(DefaultSchema.kt:39)
	at com.apurebase.kgraphql.schema.Schema$DefaultImpls.execute(Schema.kt:10)
	at com.apurebase.kgraphql.schema.DefaultSchema.execute(DefaultSchema.kt:21)
	at com.apurebase.kgraphql.schema.Schema$executeBlocking$1.invokeSuspend(Schema.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:271)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.apurebase.kgraphql.schema.Schema$DefaultImpls.executeBlocking(Schema.kt:12)
	at com.apurebase.kgraphql.schema.DefaultSchema.executeBlocking(DefaultSchema.kt:21)
	at com.apurebase.kgraphql.schema.Schema$DefaultImpls.executeBlocking$default(Schema.kt:12)
	at fnb.MainKt.main(Main.kt:6)
	at fnb.MainKt.main(Main.kt)`

**Comment by jeggy** [comment]
This is because you are trying to call a `Mutation` resolver from the `Query` type.

If not specified it will always default to Query.  What you want is to write a query like this:

```graphql
mutation {
  deleteLocation(id: "ffffff")
}
```
While this is what you have in your code:
```graphql
{
  mutation {
    deleteLocation(id: "ffffff")
  }
}
```

**Comment by MattLangsenkamp** [comment]
ahh yes always the simplest of mistakes. Thanks for clearing this up
