### ISSUE TITLE
"Generic types are not supported by GraphQL"

### ISSUE THREAD

**Issue by Digital-Nomad** [aPureBase/KGraphQL#154]
I am running into this error in my project:

```
Exception in thread "main" com.apurebase.kgraphql.schema.SchemaException: Generic types are not supported by GraphQL, found kotlin.collections.Map<org.jetbrains.exposed.sql.Expression<*>, kotlin.Int>
	at com.apurebase.kgraphql.schema.structure.SchemaCompilation.handlePossiblyWrappedType(SchemaCompilation.kt:168)
	at com.apurebase.kgraphql.schema.structure.SchemaCompilation.handleKotlinProperty(SchemaCompilation.kt:372)
```
My project is located [here](https://gitlab.com/goofy3785/thedrewreport). If you take a look at my ExposedFeed.kt, you can see I setup the Exposed DAO classes as they are shown in the Exposed examples but in your example code you use `data class` and you don't need to define the type it seems. Is this why I am running into this error?

**Comment by jeggy** [comment]
I haven't tested KGraphQL integration with Exposed before. But I can see they don't work so well together 😮

The issue is that your `ExposedFeed` class is extending the `IntEntity` which is extending [`Entity<Int>`](https://github.com/JetBrains/Exposed/blob/master/exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt) and this class provided by exposed includes some public fields that KGraphQL is trying to make available on your GraphQL Type. 

KGraphQL has an option to ignore fields on a specific type. To get this to work you would need to specify this on all of your exposed types
```kotlin
// 1kotlin classes need to be registered with "type" method
// to be included in created schema type system
// class Character is automatically included,
// as it is return type of both created queries
type<ExposedFeed> {
    ExposedFeed::id.ignore()
    ExposedFeed::klass.ignore()
    ExposedFeed::db.ignore()
    ExposedFeed::writeValues.ignore()
    ExposedFeed::_readValues.ignore()
    ExposedFeed::readValues.ignore()
}
type<ExposedEntry> {
    ExposedEntry::id.ignore()
    ExposedEntry::klass.ignore()
    ExposedEntry::db.ignore()
    ExposedEntry::writeValues.ignore()
    ExposedEntry::_readValues.ignore()
    ExposedEntry::readValues.ignore()
}
```

**Comment by Digital-Nomad** [comment]
Well you use it in the sample code in the repo just that you do it a little differently by defining a 'data class' instead of doing what they did in the exposed documentation and it works. 

for example:
https://github.com/aPureBase/KGraphQL/blob/main/kgraphql-example/src/main/kotlin/com/apurebase/kgraphql/model/UFOSightings.kt
and 
https://github.com/JetBrains/Exposed/wiki/DAO
