### ISSUE TITLE
Compatibility issue: SchemaException for type with a UUID

### ISSUE THREAD

**Issue by StefanHub** [aPureBase/KGraphQL#29]
I was switching from com.github.pgutkowski:kgraphql:0.3.0' to 'com.apurebase:kgraphql:0.5.1'.
After that I got the following exception:

    Caused by: com.apurebase.kgraphql.schema.SchemaException: An Object type must define one or more fields. Found none on type UUID
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.handleObjectType(SchemaCompilation.kt:234)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.access$handleObjectType(SchemaCompilation.kt:32)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation$handleRawType$typeCreator$1.invoke(SchemaCompilation.kt:183)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation$handleRawType$typeCreator$1.invoke(SchemaCompilation.kt:32)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.handleRawType(SchemaCompilation.kt:190)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.handleSimpleType(SchemaCompilation.kt:161)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.handlePossiblyWrappedType(SchemaCompilation.kt:149)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.handleKotlinProperty(SchemaCompilation.kt:301)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.handleObjectType(SchemaCompilation.kt:213)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.access$handleObjectType(SchemaCompilation.kt:32)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation$handleRawType$typeCreator$1.invoke(SchemaCompilation.kt:183)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation$handleRawType$typeCreator$1.invoke(SchemaCompilation.kt:32)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.handleRawType(SchemaCompilation.kt:190)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.handleSimpleType(SchemaCompilation.kt:161)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.handleCollectionType(SchemaCompilation.kt:156)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.handlePossiblyWrappedType(SchemaCompilation.kt:145)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.handleOperation(SchemaCompilation.kt:132)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.handleQueries(SchemaCompilation.kt:113)
    	at com.apurebase.kgraphql.schema.structure2.SchemaCompilation.perform(SchemaCompilation.kt:56)
    	at com.apurebase.kgraphql.schema.dsl.SchemaBuilder.build(SchemaBuilder.kt:26)
    	at com.apurebase.kgraphql.KGraphQL$Companion.schema(KGraphQL.kt:8)
    	at timebox.graphql.GrapQLKt.<clinit>(GrapQL.kt:21)
    	... 40 more

Unfortunatly it does not tell which type is causing the error, but I have just two classes with a UUID property. However, for these classes I have a property resolver that handles the UUID property:

    type<TimeEntry> {
         description = "Time entries ..."
 
         property<String?>("id") {
             resolver { timeEntry ->
                 timeEntry.id.toString()
             }
         }
       ...

the timeEntry.id is of type UUID.

Any idea!

**Comment by jeggy** [comment]
What kotlin type is UUID?

**Comment by jeggy** [comment]
This works fine for me: https://gist.github.com/jeggy/0b514439a9b2588a28b62433c2da4713

**Comment by StefanHub** [comment]
Sorry, it is java.util.UUID

**Comment by jeggy** [comment]
I'm not sure how it worked for you before, but I think would would make sense to use scalars here:

```kotlin
stringScalar<UUID> {
   serialize = UUID::toString
   deserialize = UUID::fromString
}
```
And then just remove the `property<String?>("id")`

**Comment by StefanHub** [comment]
This is definitely much better, but I do not understand why your fork behaves differently.

**Comment by jeggy** [comment]
I found the root cause of it 😃 

As the error states `An Object type must define one or more fields`. The `UUID` has no public fields on it, and after this change, that will report an error: https://github.com/aPureBase/KGraphQL/pull/25

**Comment by StefanHub** [comment]
Ok, that causes the "incompatibility" :-)

However, it would be fine if the error message could name the "Object type", e.g. "The object type java.util.UUID has no ...

**Comment by jeggy** [comment]
It currently does: `An Object type must define one or more fields. Found none on type UUID`

Maybe we could re-word it to something like `The 'UUID' object type must define atleast one or more fields`, so it mentions the object type near the beginning the sentence.

**Comment by StefanHub** [comment]
Damned! I did not remember this. Sorry!

Yes, your proposal sounds good to me.

**Comment by jeggy** [comment]
Haha, no problem 😄 

Always welcome to post more issues here.
