### ISSUE TITLE
Ability to return union type in query/mutation resolver

### ISSUE THREAD

**Issue by FabioGimmillaro** [aPureBase/KGraphQL#83]
Hey guys,

I just tested if it was possible to directly return a union type within a query or mutation resolver.

I only got it working with an ugly compromise: 
It only works when the base class I use for the union-type declares at least one field....
Otherwise I get the following _SchemaException_:
**An Object type must define one or more fields. Found none on type A**

This is the code I wrote:
```
// Only works if A has at least one property
sealed class A(val a: A? = null) {
    data class B(val i: Int) : A()
    data class C(val s: String) : A()
    data class D(val b: Boolean) : A()
}

inline fun <reified T> SchemaBuilder.unionTypeFromSealedClass() =
    unionType(T::class.simpleName!!) {
        T::class.nestedClasses.forEach {
            type(it)
        }
    }


KGraphQL.schema {
    unionTypeFromSealedClass<A>()
    query("returnUnion") {
        resolver { ctx: Context, isB: Boolean ->
            if(isB) {
                A.B(1)
            } else {
                A.C("String")
            }
        }
    }
}
```

Another solution would be to wrap the union type within another object as a union property.

**Comment by jeggy** [comment]
Thanks for reporting this. 

The problem here is because the resolver is trying to return a type of `A` while it actually should return your union type.

I will fix this by having built in sealed classes support. 

So something like this will just work out of the box:
```kotlin
// Only works if A has at least one property
sealed class A {
    data class B(val i: Int) : A()
    data class C(val s: String) : A()
    data class D(val b: Boolean) : A()
}

KGraphQL.schema {
    query("returnUnion") {
        resolver { ctx: Context, isB: Boolean ->
            if(isB) {
                A.B(1)
            } else {
                A.C("String")
            }
        }
    }
}
```

**Comment by jeggy** [comment]
This now works out of the box with sealed classes:
https://kgraphql.in/docs/reference/type-system/unions/#sealed-class

**Comment by Leopard2A5** [comment]
Hey @jeggy, could it be that `unionType` doesn't work properly with the `__typename` field?

I have this sealed class here:
```kotlin
sealed class ContactStatus {
    data class NotInvited(
        val dummy: String = "dummy" // because no empty types in gql
    ) : ContactStatus()

    data class Invited(
        val invitationId: String,
        val invitedAt: Instant
    ) : ContactStatus()

    data class Onboarded(
        val onboardedAt: Instant = Instant.now(),
        val userId: String
    ) : ContactStatus()
}
```

which can be queried fine like so:
```
contactStatus {
    ... on NotInvited {
        dummy
        __typename
    }
    ... on Invited {
        invitedAt
        invitationId
        __typename
    }
    ... on Onboarded {
        onboardedAt
        userId
        __typename
    }
}
```

but fails miserably when i put the __typename field outside the specific type queries:
```
contactStatus {
    ... on NotInvited {
        dummy
    }
    ... on Invited {
        invitedAt
        invitationId
    }
    ... on Onboarded {
        onboardedAt
        userId
    }
    __typename
}
```

```
com.apurebase.kgraphql.GraphQLError: Property __typename on ContactStatus does not exist
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelection(RequestInterpreter.kt:149)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelection$default(RequestInterpreter.kt:147)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelectionFieldOrFragment(RequestInterpreter.kt:144)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleReturnTypeChildOrFragment(RequestInterpreter.kt:121)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleReturnType(RequestInterpreter.kt:108)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleReturnType(RequestInterpreter.kt:101)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelection(RequestInterpreter.kt:160)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelection$default(RequestInterpreter.kt:147)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelectionFieldOrFragment(RequestInterpreter.kt:144)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.access$handleSelectionFieldOrFragment(RequestInterpreter.kt:23)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter$InterpreterContext.get(RequestInterpreter.kt:42)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.findFragmentType(RequestInterpreter.kt:125)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelectionFieldOrFragment(RequestInterpreter.kt:143)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleReturnTypeChildOrFragment(RequestInterpreter.kt:121)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleReturnType(RequestInterpreter.kt:108)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleReturnType(RequestInterpreter.kt:101)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelection(RequestInterpreter.kt:160)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelection$default(RequestInterpreter.kt:147)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelectionFieldOrFragment(RequestInterpreter.kt:144)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.access$handleSelectionFieldOrFragment(RequestInterpreter.kt:23)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter$InterpreterContext.get(RequestInterpreter.kt:42)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.findFragmentType(RequestInterpreter.kt:125)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelectionFieldOrFragment(RequestInterpreter.kt:143)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleReturnTypeChildOrFragment(RequestInterpreter.kt:121)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleReturnType(RequestInterpreter.kt:108)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleReturnType(RequestInterpreter.kt:101)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelection(RequestInterpreter.kt:160)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.createExecutionPlan(RequestInterpreter.kt:93)
	at com.apurebase.kgraphql.schema.DefaultSchema$execute$2.invokeSuspend(DefaultSchema.kt:51)
	at com.apurebase.kgraphql.schema.DefaultSchema$execute$2.invoke(DefaultSchema.kt)
```
